package db.model;

public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.id
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.platformId
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    private Integer platformid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.platformName
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    private String platformname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.platform_account
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    private String platformAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.deviceId
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    private String deviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.imei
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    private String imei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.idfa
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    private String idfa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.mac
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    private String mac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.resVer
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    private Integer resver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.exeVer
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    private Integer exever;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.gameVer
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    private Integer gamever;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.protocolVer
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    private Integer protocolver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.createTime
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    private Integer createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.lastLogintime
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    private Integer lastlogintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.gsid
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    private Integer gsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.lastLogoutTime
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    private Integer lastlogouttime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.id
     *
     * @return the value of account.id
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.id
     *
     * @param id the value for account.id
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account
     *
     * @return the value of account.account
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account
     *
     * @param account the value for account.account
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.platformId
     *
     * @return the value of account.platformId
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public Integer getPlatformid() {
        return platformid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.platformId
     *
     * @param platformid the value for account.platformId
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public void setPlatformid(Integer platformid) {
        this.platformid = platformid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.platformName
     *
     * @return the value of account.platformName
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public String getPlatformname() {
        return platformname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.platformName
     *
     * @param platformname the value for account.platformName
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public void setPlatformname(String platformname) {
        this.platformname = platformname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.platform_account
     *
     * @return the value of account.platform_account
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public String getPlatformAccount() {
        return platformAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.platform_account
     *
     * @param platformAccount the value for account.platform_account
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public void setPlatformAccount(String platformAccount) {
        this.platformAccount = platformAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.deviceId
     *
     * @return the value of account.deviceId
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public String getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.deviceId
     *
     * @param deviceid the value for account.deviceId
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public void setDeviceid(String deviceid) {
        this.deviceid = deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.imei
     *
     * @return the value of account.imei
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.imei
     *
     * @param imei the value for account.imei
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public void setImei(String imei) {
        this.imei = imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.idfa
     *
     * @return the value of account.idfa
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public String getIdfa() {
        return idfa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.idfa
     *
     * @param idfa the value for account.idfa
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public void setIdfa(String idfa) {
        this.idfa = idfa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.mac
     *
     * @return the value of account.mac
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.mac
     *
     * @param mac the value for account.mac
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public void setMac(String mac) {
        this.mac = mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.resVer
     *
     * @return the value of account.resVer
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public Integer getResver() {
        return resver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.resVer
     *
     * @param resver the value for account.resVer
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public void setResver(Integer resver) {
        this.resver = resver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.exeVer
     *
     * @return the value of account.exeVer
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public Integer getExever() {
        return exever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.exeVer
     *
     * @param exever the value for account.exeVer
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public void setExever(Integer exever) {
        this.exever = exever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.gameVer
     *
     * @return the value of account.gameVer
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public Integer getGamever() {
        return gamever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.gameVer
     *
     * @param gamever the value for account.gameVer
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public void setGamever(Integer gamever) {
        this.gamever = gamever;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.protocolVer
     *
     * @return the value of account.protocolVer
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public Integer getProtocolver() {
        return protocolver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.protocolVer
     *
     * @param protocolver the value for account.protocolVer
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public void setProtocolver(Integer protocolver) {
        this.protocolver = protocolver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.createTime
     *
     * @return the value of account.createTime
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public Integer getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.createTime
     *
     * @param createtime the value for account.createTime
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public void setCreatetime(Integer createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.lastLogintime
     *
     * @return the value of account.lastLogintime
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public Integer getLastlogintime() {
        return lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.lastLogintime
     *
     * @param lastlogintime the value for account.lastLogintime
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public void setLastlogintime(Integer lastlogintime) {
        this.lastlogintime = lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.gsid
     *
     * @return the value of account.gsid
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public Integer getGsid() {
        return gsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.gsid
     *
     * @param gsid the value for account.gsid
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public void setGsid(Integer gsid) {
        this.gsid = gsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.lastLogoutTime
     *
     * @return the value of account.lastLogoutTime
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public Integer getLastlogouttime() {
        return lastlogouttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.lastLogoutTime
     *
     * @param lastlogouttime the value for account.lastLogoutTime
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public void setLastlogouttime(Integer lastlogouttime) {
        this.lastlogouttime = lastlogouttime;
    }
}