package db.model;

import java.util.ArrayList;
import java.util.List;

public class AccountExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public AccountExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table account
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAccountIsNull() {
            addCriterion("account is null");
            return (Criteria) this;
        }

        public Criteria andAccountIsNotNull() {
            addCriterion("account is not null");
            return (Criteria) this;
        }

        public Criteria andAccountEqualTo(String value) {
            addCriterion("account =", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotEqualTo(String value) {
            addCriterion("account <>", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountGreaterThan(String value) {
            addCriterion("account >", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountGreaterThanOrEqualTo(String value) {
            addCriterion("account >=", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLessThan(String value) {
            addCriterion("account <", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLessThanOrEqualTo(String value) {
            addCriterion("account <=", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLike(String value) {
            addCriterion("account like", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotLike(String value) {
            addCriterion("account not like", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountIn(List<String> values) {
            addCriterion("account in", values, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotIn(List<String> values) {
            addCriterion("account not in", values, "account");
            return (Criteria) this;
        }

        public Criteria andAccountBetween(String value1, String value2) {
            addCriterion("account between", value1, value2, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotBetween(String value1, String value2) {
            addCriterion("account not between", value1, value2, "account");
            return (Criteria) this;
        }

        public Criteria andPlatformidIsNull() {
            addCriterion("platformId is null");
            return (Criteria) this;
        }

        public Criteria andPlatformidIsNotNull() {
            addCriterion("platformId is not null");
            return (Criteria) this;
        }

        public Criteria andPlatformidEqualTo(Integer value) {
            addCriterion("platformId =", value, "platformid");
            return (Criteria) this;
        }

        public Criteria andPlatformidNotEqualTo(Integer value) {
            addCriterion("platformId <>", value, "platformid");
            return (Criteria) this;
        }

        public Criteria andPlatformidGreaterThan(Integer value) {
            addCriterion("platformId >", value, "platformid");
            return (Criteria) this;
        }

        public Criteria andPlatformidGreaterThanOrEqualTo(Integer value) {
            addCriterion("platformId >=", value, "platformid");
            return (Criteria) this;
        }

        public Criteria andPlatformidLessThan(Integer value) {
            addCriterion("platformId <", value, "platformid");
            return (Criteria) this;
        }

        public Criteria andPlatformidLessThanOrEqualTo(Integer value) {
            addCriterion("platformId <=", value, "platformid");
            return (Criteria) this;
        }

        public Criteria andPlatformidIn(List<Integer> values) {
            addCriterion("platformId in", values, "platformid");
            return (Criteria) this;
        }

        public Criteria andPlatformidNotIn(List<Integer> values) {
            addCriterion("platformId not in", values, "platformid");
            return (Criteria) this;
        }

        public Criteria andPlatformidBetween(Integer value1, Integer value2) {
            addCriterion("platformId between", value1, value2, "platformid");
            return (Criteria) this;
        }

        public Criteria andPlatformidNotBetween(Integer value1, Integer value2) {
            addCriterion("platformId not between", value1, value2, "platformid");
            return (Criteria) this;
        }

        public Criteria andPlatformnameIsNull() {
            addCriterion("platformName is null");
            return (Criteria) this;
        }

        public Criteria andPlatformnameIsNotNull() {
            addCriterion("platformName is not null");
            return (Criteria) this;
        }

        public Criteria andPlatformnameEqualTo(String value) {
            addCriterion("platformName =", value, "platformname");
            return (Criteria) this;
        }

        public Criteria andPlatformnameNotEqualTo(String value) {
            addCriterion("platformName <>", value, "platformname");
            return (Criteria) this;
        }

        public Criteria andPlatformnameGreaterThan(String value) {
            addCriterion("platformName >", value, "platformname");
            return (Criteria) this;
        }

        public Criteria andPlatformnameGreaterThanOrEqualTo(String value) {
            addCriterion("platformName >=", value, "platformname");
            return (Criteria) this;
        }

        public Criteria andPlatformnameLessThan(String value) {
            addCriterion("platformName <", value, "platformname");
            return (Criteria) this;
        }

        public Criteria andPlatformnameLessThanOrEqualTo(String value) {
            addCriterion("platformName <=", value, "platformname");
            return (Criteria) this;
        }

        public Criteria andPlatformnameLike(String value) {
            addCriterion("platformName like", value, "platformname");
            return (Criteria) this;
        }

        public Criteria andPlatformnameNotLike(String value) {
            addCriterion("platformName not like", value, "platformname");
            return (Criteria) this;
        }

        public Criteria andPlatformnameIn(List<String> values) {
            addCriterion("platformName in", values, "platformname");
            return (Criteria) this;
        }

        public Criteria andPlatformnameNotIn(List<String> values) {
            addCriterion("platformName not in", values, "platformname");
            return (Criteria) this;
        }

        public Criteria andPlatformnameBetween(String value1, String value2) {
            addCriterion("platformName between", value1, value2, "platformname");
            return (Criteria) this;
        }

        public Criteria andPlatformnameNotBetween(String value1, String value2) {
            addCriterion("platformName not between", value1, value2, "platformname");
            return (Criteria) this;
        }

        public Criteria andPlatformAccountIsNull() {
            addCriterion("platform_account is null");
            return (Criteria) this;
        }

        public Criteria andPlatformAccountIsNotNull() {
            addCriterion("platform_account is not null");
            return (Criteria) this;
        }

        public Criteria andPlatformAccountEqualTo(String value) {
            addCriterion("platform_account =", value, "platformAccount");
            return (Criteria) this;
        }

        public Criteria andPlatformAccountNotEqualTo(String value) {
            addCriterion("platform_account <>", value, "platformAccount");
            return (Criteria) this;
        }

        public Criteria andPlatformAccountGreaterThan(String value) {
            addCriterion("platform_account >", value, "platformAccount");
            return (Criteria) this;
        }

        public Criteria andPlatformAccountGreaterThanOrEqualTo(String value) {
            addCriterion("platform_account >=", value, "platformAccount");
            return (Criteria) this;
        }

        public Criteria andPlatformAccountLessThan(String value) {
            addCriterion("platform_account <", value, "platformAccount");
            return (Criteria) this;
        }

        public Criteria andPlatformAccountLessThanOrEqualTo(String value) {
            addCriterion("platform_account <=", value, "platformAccount");
            return (Criteria) this;
        }

        public Criteria andPlatformAccountLike(String value) {
            addCriterion("platform_account like", value, "platformAccount");
            return (Criteria) this;
        }

        public Criteria andPlatformAccountNotLike(String value) {
            addCriterion("platform_account not like", value, "platformAccount");
            return (Criteria) this;
        }

        public Criteria andPlatformAccountIn(List<String> values) {
            addCriterion("platform_account in", values, "platformAccount");
            return (Criteria) this;
        }

        public Criteria andPlatformAccountNotIn(List<String> values) {
            addCriterion("platform_account not in", values, "platformAccount");
            return (Criteria) this;
        }

        public Criteria andPlatformAccountBetween(String value1, String value2) {
            addCriterion("platform_account between", value1, value2, "platformAccount");
            return (Criteria) this;
        }

        public Criteria andPlatformAccountNotBetween(String value1, String value2) {
            addCriterion("platform_account not between", value1, value2, "platformAccount");
            return (Criteria) this;
        }

        public Criteria andDeviceidIsNull() {
            addCriterion("deviceId is null");
            return (Criteria) this;
        }

        public Criteria andDeviceidIsNotNull() {
            addCriterion("deviceId is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceidEqualTo(String value) {
            addCriterion("deviceId =", value, "deviceid");
            return (Criteria) this;
        }

        public Criteria andDeviceidNotEqualTo(String value) {
            addCriterion("deviceId <>", value, "deviceid");
            return (Criteria) this;
        }

        public Criteria andDeviceidGreaterThan(String value) {
            addCriterion("deviceId >", value, "deviceid");
            return (Criteria) this;
        }

        public Criteria andDeviceidGreaterThanOrEqualTo(String value) {
            addCriterion("deviceId >=", value, "deviceid");
            return (Criteria) this;
        }

        public Criteria andDeviceidLessThan(String value) {
            addCriterion("deviceId <", value, "deviceid");
            return (Criteria) this;
        }

        public Criteria andDeviceidLessThanOrEqualTo(String value) {
            addCriterion("deviceId <=", value, "deviceid");
            return (Criteria) this;
        }

        public Criteria andDeviceidLike(String value) {
            addCriterion("deviceId like", value, "deviceid");
            return (Criteria) this;
        }

        public Criteria andDeviceidNotLike(String value) {
            addCriterion("deviceId not like", value, "deviceid");
            return (Criteria) this;
        }

        public Criteria andDeviceidIn(List<String> values) {
            addCriterion("deviceId in", values, "deviceid");
            return (Criteria) this;
        }

        public Criteria andDeviceidNotIn(List<String> values) {
            addCriterion("deviceId not in", values, "deviceid");
            return (Criteria) this;
        }

        public Criteria andDeviceidBetween(String value1, String value2) {
            addCriterion("deviceId between", value1, value2, "deviceid");
            return (Criteria) this;
        }

        public Criteria andDeviceidNotBetween(String value1, String value2) {
            addCriterion("deviceId not between", value1, value2, "deviceid");
            return (Criteria) this;
        }

        public Criteria andImeiIsNull() {
            addCriterion("imei is null");
            return (Criteria) this;
        }

        public Criteria andImeiIsNotNull() {
            addCriterion("imei is not null");
            return (Criteria) this;
        }

        public Criteria andImeiEqualTo(String value) {
            addCriterion("imei =", value, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiNotEqualTo(String value) {
            addCriterion("imei <>", value, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiGreaterThan(String value) {
            addCriterion("imei >", value, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiGreaterThanOrEqualTo(String value) {
            addCriterion("imei >=", value, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiLessThan(String value) {
            addCriterion("imei <", value, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiLessThanOrEqualTo(String value) {
            addCriterion("imei <=", value, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiLike(String value) {
            addCriterion("imei like", value, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiNotLike(String value) {
            addCriterion("imei not like", value, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiIn(List<String> values) {
            addCriterion("imei in", values, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiNotIn(List<String> values) {
            addCriterion("imei not in", values, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiBetween(String value1, String value2) {
            addCriterion("imei between", value1, value2, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiNotBetween(String value1, String value2) {
            addCriterion("imei not between", value1, value2, "imei");
            return (Criteria) this;
        }

        public Criteria andIdfaIsNull() {
            addCriterion("idfa is null");
            return (Criteria) this;
        }

        public Criteria andIdfaIsNotNull() {
            addCriterion("idfa is not null");
            return (Criteria) this;
        }

        public Criteria andIdfaEqualTo(String value) {
            addCriterion("idfa =", value, "idfa");
            return (Criteria) this;
        }

        public Criteria andIdfaNotEqualTo(String value) {
            addCriterion("idfa <>", value, "idfa");
            return (Criteria) this;
        }

        public Criteria andIdfaGreaterThan(String value) {
            addCriterion("idfa >", value, "idfa");
            return (Criteria) this;
        }

        public Criteria andIdfaGreaterThanOrEqualTo(String value) {
            addCriterion("idfa >=", value, "idfa");
            return (Criteria) this;
        }

        public Criteria andIdfaLessThan(String value) {
            addCriterion("idfa <", value, "idfa");
            return (Criteria) this;
        }

        public Criteria andIdfaLessThanOrEqualTo(String value) {
            addCriterion("idfa <=", value, "idfa");
            return (Criteria) this;
        }

        public Criteria andIdfaLike(String value) {
            addCriterion("idfa like", value, "idfa");
            return (Criteria) this;
        }

        public Criteria andIdfaNotLike(String value) {
            addCriterion("idfa not like", value, "idfa");
            return (Criteria) this;
        }

        public Criteria andIdfaIn(List<String> values) {
            addCriterion("idfa in", values, "idfa");
            return (Criteria) this;
        }

        public Criteria andIdfaNotIn(List<String> values) {
            addCriterion("idfa not in", values, "idfa");
            return (Criteria) this;
        }

        public Criteria andIdfaBetween(String value1, String value2) {
            addCriterion("idfa between", value1, value2, "idfa");
            return (Criteria) this;
        }

        public Criteria andIdfaNotBetween(String value1, String value2) {
            addCriterion("idfa not between", value1, value2, "idfa");
            return (Criteria) this;
        }

        public Criteria andMacIsNull() {
            addCriterion("mac is null");
            return (Criteria) this;
        }

        public Criteria andMacIsNotNull() {
            addCriterion("mac is not null");
            return (Criteria) this;
        }

        public Criteria andMacEqualTo(String value) {
            addCriterion("mac =", value, "mac");
            return (Criteria) this;
        }

        public Criteria andMacNotEqualTo(String value) {
            addCriterion("mac <>", value, "mac");
            return (Criteria) this;
        }

        public Criteria andMacGreaterThan(String value) {
            addCriterion("mac >", value, "mac");
            return (Criteria) this;
        }

        public Criteria andMacGreaterThanOrEqualTo(String value) {
            addCriterion("mac >=", value, "mac");
            return (Criteria) this;
        }

        public Criteria andMacLessThan(String value) {
            addCriterion("mac <", value, "mac");
            return (Criteria) this;
        }

        public Criteria andMacLessThanOrEqualTo(String value) {
            addCriterion("mac <=", value, "mac");
            return (Criteria) this;
        }

        public Criteria andMacLike(String value) {
            addCriterion("mac like", value, "mac");
            return (Criteria) this;
        }

        public Criteria andMacNotLike(String value) {
            addCriterion("mac not like", value, "mac");
            return (Criteria) this;
        }

        public Criteria andMacIn(List<String> values) {
            addCriterion("mac in", values, "mac");
            return (Criteria) this;
        }

        public Criteria andMacNotIn(List<String> values) {
            addCriterion("mac not in", values, "mac");
            return (Criteria) this;
        }

        public Criteria andMacBetween(String value1, String value2) {
            addCriterion("mac between", value1, value2, "mac");
            return (Criteria) this;
        }

        public Criteria andMacNotBetween(String value1, String value2) {
            addCriterion("mac not between", value1, value2, "mac");
            return (Criteria) this;
        }

        public Criteria andResverIsNull() {
            addCriterion("resVer is null");
            return (Criteria) this;
        }

        public Criteria andResverIsNotNull() {
            addCriterion("resVer is not null");
            return (Criteria) this;
        }

        public Criteria andResverEqualTo(Integer value) {
            addCriterion("resVer =", value, "resver");
            return (Criteria) this;
        }

        public Criteria andResverNotEqualTo(Integer value) {
            addCriterion("resVer <>", value, "resver");
            return (Criteria) this;
        }

        public Criteria andResverGreaterThan(Integer value) {
            addCriterion("resVer >", value, "resver");
            return (Criteria) this;
        }

        public Criteria andResverGreaterThanOrEqualTo(Integer value) {
            addCriterion("resVer >=", value, "resver");
            return (Criteria) this;
        }

        public Criteria andResverLessThan(Integer value) {
            addCriterion("resVer <", value, "resver");
            return (Criteria) this;
        }

        public Criteria andResverLessThanOrEqualTo(Integer value) {
            addCriterion("resVer <=", value, "resver");
            return (Criteria) this;
        }

        public Criteria andResverIn(List<Integer> values) {
            addCriterion("resVer in", values, "resver");
            return (Criteria) this;
        }

        public Criteria andResverNotIn(List<Integer> values) {
            addCriterion("resVer not in", values, "resver");
            return (Criteria) this;
        }

        public Criteria andResverBetween(Integer value1, Integer value2) {
            addCriterion("resVer between", value1, value2, "resver");
            return (Criteria) this;
        }

        public Criteria andResverNotBetween(Integer value1, Integer value2) {
            addCriterion("resVer not between", value1, value2, "resver");
            return (Criteria) this;
        }

        public Criteria andExeverIsNull() {
            addCriterion("exeVer is null");
            return (Criteria) this;
        }

        public Criteria andExeverIsNotNull() {
            addCriterion("exeVer is not null");
            return (Criteria) this;
        }

        public Criteria andExeverEqualTo(Integer value) {
            addCriterion("exeVer =", value, "exever");
            return (Criteria) this;
        }

        public Criteria andExeverNotEqualTo(Integer value) {
            addCriterion("exeVer <>", value, "exever");
            return (Criteria) this;
        }

        public Criteria andExeverGreaterThan(Integer value) {
            addCriterion("exeVer >", value, "exever");
            return (Criteria) this;
        }

        public Criteria andExeverGreaterThanOrEqualTo(Integer value) {
            addCriterion("exeVer >=", value, "exever");
            return (Criteria) this;
        }

        public Criteria andExeverLessThan(Integer value) {
            addCriterion("exeVer <", value, "exever");
            return (Criteria) this;
        }

        public Criteria andExeverLessThanOrEqualTo(Integer value) {
            addCriterion("exeVer <=", value, "exever");
            return (Criteria) this;
        }

        public Criteria andExeverIn(List<Integer> values) {
            addCriterion("exeVer in", values, "exever");
            return (Criteria) this;
        }

        public Criteria andExeverNotIn(List<Integer> values) {
            addCriterion("exeVer not in", values, "exever");
            return (Criteria) this;
        }

        public Criteria andExeverBetween(Integer value1, Integer value2) {
            addCriterion("exeVer between", value1, value2, "exever");
            return (Criteria) this;
        }

        public Criteria andExeverNotBetween(Integer value1, Integer value2) {
            addCriterion("exeVer not between", value1, value2, "exever");
            return (Criteria) this;
        }

        public Criteria andGameverIsNull() {
            addCriterion("gameVer is null");
            return (Criteria) this;
        }

        public Criteria andGameverIsNotNull() {
            addCriterion("gameVer is not null");
            return (Criteria) this;
        }

        public Criteria andGameverEqualTo(Integer value) {
            addCriterion("gameVer =", value, "gamever");
            return (Criteria) this;
        }

        public Criteria andGameverNotEqualTo(Integer value) {
            addCriterion("gameVer <>", value, "gamever");
            return (Criteria) this;
        }

        public Criteria andGameverGreaterThan(Integer value) {
            addCriterion("gameVer >", value, "gamever");
            return (Criteria) this;
        }

        public Criteria andGameverGreaterThanOrEqualTo(Integer value) {
            addCriterion("gameVer >=", value, "gamever");
            return (Criteria) this;
        }

        public Criteria andGameverLessThan(Integer value) {
            addCriterion("gameVer <", value, "gamever");
            return (Criteria) this;
        }

        public Criteria andGameverLessThanOrEqualTo(Integer value) {
            addCriterion("gameVer <=", value, "gamever");
            return (Criteria) this;
        }

        public Criteria andGameverIn(List<Integer> values) {
            addCriterion("gameVer in", values, "gamever");
            return (Criteria) this;
        }

        public Criteria andGameverNotIn(List<Integer> values) {
            addCriterion("gameVer not in", values, "gamever");
            return (Criteria) this;
        }

        public Criteria andGameverBetween(Integer value1, Integer value2) {
            addCriterion("gameVer between", value1, value2, "gamever");
            return (Criteria) this;
        }

        public Criteria andGameverNotBetween(Integer value1, Integer value2) {
            addCriterion("gameVer not between", value1, value2, "gamever");
            return (Criteria) this;
        }

        public Criteria andProtocolverIsNull() {
            addCriterion("protocolVer is null");
            return (Criteria) this;
        }

        public Criteria andProtocolverIsNotNull() {
            addCriterion("protocolVer is not null");
            return (Criteria) this;
        }

        public Criteria andProtocolverEqualTo(Integer value) {
            addCriterion("protocolVer =", value, "protocolver");
            return (Criteria) this;
        }

        public Criteria andProtocolverNotEqualTo(Integer value) {
            addCriterion("protocolVer <>", value, "protocolver");
            return (Criteria) this;
        }

        public Criteria andProtocolverGreaterThan(Integer value) {
            addCriterion("protocolVer >", value, "protocolver");
            return (Criteria) this;
        }

        public Criteria andProtocolverGreaterThanOrEqualTo(Integer value) {
            addCriterion("protocolVer >=", value, "protocolver");
            return (Criteria) this;
        }

        public Criteria andProtocolverLessThan(Integer value) {
            addCriterion("protocolVer <", value, "protocolver");
            return (Criteria) this;
        }

        public Criteria andProtocolverLessThanOrEqualTo(Integer value) {
            addCriterion("protocolVer <=", value, "protocolver");
            return (Criteria) this;
        }

        public Criteria andProtocolverIn(List<Integer> values) {
            addCriterion("protocolVer in", values, "protocolver");
            return (Criteria) this;
        }

        public Criteria andProtocolverNotIn(List<Integer> values) {
            addCriterion("protocolVer not in", values, "protocolver");
            return (Criteria) this;
        }

        public Criteria andProtocolverBetween(Integer value1, Integer value2) {
            addCriterion("protocolVer between", value1, value2, "protocolver");
            return (Criteria) this;
        }

        public Criteria andProtocolverNotBetween(Integer value1, Integer value2) {
            addCriterion("protocolVer not between", value1, value2, "protocolver");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Integer value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Integer value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Integer value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Integer value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Integer value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Integer> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Integer> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Integer value1, Integer value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Integer value1, Integer value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeIsNull() {
            addCriterion("lastLogintime is null");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeIsNotNull() {
            addCriterion("lastLogintime is not null");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeEqualTo(Integer value) {
            addCriterion("lastLogintime =", value, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeNotEqualTo(Integer value) {
            addCriterion("lastLogintime <>", value, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeGreaterThan(Integer value) {
            addCriterion("lastLogintime >", value, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("lastLogintime >=", value, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeLessThan(Integer value) {
            addCriterion("lastLogintime <", value, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeLessThanOrEqualTo(Integer value) {
            addCriterion("lastLogintime <=", value, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeIn(List<Integer> values) {
            addCriterion("lastLogintime in", values, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeNotIn(List<Integer> values) {
            addCriterion("lastLogintime not in", values, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeBetween(Integer value1, Integer value2) {
            addCriterion("lastLogintime between", value1, value2, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeNotBetween(Integer value1, Integer value2) {
            addCriterion("lastLogintime not between", value1, value2, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andGsidIsNull() {
            addCriterion("gsid is null");
            return (Criteria) this;
        }

        public Criteria andGsidIsNotNull() {
            addCriterion("gsid is not null");
            return (Criteria) this;
        }

        public Criteria andGsidEqualTo(Integer value) {
            addCriterion("gsid =", value, "gsid");
            return (Criteria) this;
        }

        public Criteria andGsidNotEqualTo(Integer value) {
            addCriterion("gsid <>", value, "gsid");
            return (Criteria) this;
        }

        public Criteria andGsidGreaterThan(Integer value) {
            addCriterion("gsid >", value, "gsid");
            return (Criteria) this;
        }

        public Criteria andGsidGreaterThanOrEqualTo(Integer value) {
            addCriterion("gsid >=", value, "gsid");
            return (Criteria) this;
        }

        public Criteria andGsidLessThan(Integer value) {
            addCriterion("gsid <", value, "gsid");
            return (Criteria) this;
        }

        public Criteria andGsidLessThanOrEqualTo(Integer value) {
            addCriterion("gsid <=", value, "gsid");
            return (Criteria) this;
        }

        public Criteria andGsidIn(List<Integer> values) {
            addCriterion("gsid in", values, "gsid");
            return (Criteria) this;
        }

        public Criteria andGsidNotIn(List<Integer> values) {
            addCriterion("gsid not in", values, "gsid");
            return (Criteria) this;
        }

        public Criteria andGsidBetween(Integer value1, Integer value2) {
            addCriterion("gsid between", value1, value2, "gsid");
            return (Criteria) this;
        }

        public Criteria andGsidNotBetween(Integer value1, Integer value2) {
            addCriterion("gsid not between", value1, value2, "gsid");
            return (Criteria) this;
        }

        public Criteria andLastlogouttimeIsNull() {
            addCriterion("lastLogoutTime is null");
            return (Criteria) this;
        }

        public Criteria andLastlogouttimeIsNotNull() {
            addCriterion("lastLogoutTime is not null");
            return (Criteria) this;
        }

        public Criteria andLastlogouttimeEqualTo(Integer value) {
            addCriterion("lastLogoutTime =", value, "lastlogouttime");
            return (Criteria) this;
        }

        public Criteria andLastlogouttimeNotEqualTo(Integer value) {
            addCriterion("lastLogoutTime <>", value, "lastlogouttime");
            return (Criteria) this;
        }

        public Criteria andLastlogouttimeGreaterThan(Integer value) {
            addCriterion("lastLogoutTime >", value, "lastlogouttime");
            return (Criteria) this;
        }

        public Criteria andLastlogouttimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("lastLogoutTime >=", value, "lastlogouttime");
            return (Criteria) this;
        }

        public Criteria andLastlogouttimeLessThan(Integer value) {
            addCriterion("lastLogoutTime <", value, "lastlogouttime");
            return (Criteria) this;
        }

        public Criteria andLastlogouttimeLessThanOrEqualTo(Integer value) {
            addCriterion("lastLogoutTime <=", value, "lastlogouttime");
            return (Criteria) this;
        }

        public Criteria andLastlogouttimeIn(List<Integer> values) {
            addCriterion("lastLogoutTime in", values, "lastlogouttime");
            return (Criteria) this;
        }

        public Criteria andLastlogouttimeNotIn(List<Integer> values) {
            addCriterion("lastLogoutTime not in", values, "lastlogouttime");
            return (Criteria) this;
        }

        public Criteria andLastlogouttimeBetween(Integer value1, Integer value2) {
            addCriterion("lastLogoutTime between", value1, value2, "lastlogouttime");
            return (Criteria) this;
        }

        public Criteria andLastlogouttimeNotBetween(Integer value1, Integer value2) {
            addCriterion("lastLogoutTime not between", value1, value2, "lastlogouttime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table account
     *
     * @mbggenerated do_not_delete_during_merge Tue Sep 06 15:43:49 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table account
     *
     * @mbggenerated Tue Sep 06 15:43:49 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}