// Code generated by protoc-gen-go.
// source: MyMessage.proto
// DO NOT EDIT!

/*
Package google_protobuf is a generated protocol buffer package.

It is generated from these files:
	MyMessage.proto

It has these top-level messages:
	Foo
	Bar
	Baz
	OneMessage
*/
package google_protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OneMessage_Type int32

const (
	OneMessage_FOO OneMessage_Type = 0
	OneMessage_BAR OneMessage_Type = 1
	OneMessage_BAZ OneMessage_Type = 2
)

var OneMessage_Type_name = map[int32]string{
	0: "FOO",
	1: "BAR",
	2: "BAZ",
}
var OneMessage_Type_value = map[string]int32{
	"FOO": 0,
	"BAR": 1,
	"BAZ": 2,
}

func (x OneMessage_Type) String() string {
	return proto.EnumName(OneMessage_Type_name, int32(x))
}
func (OneMessage_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type Foo struct {
	SubReqID int32 `protobuf:"varint,1,opt,name=subReqID" json:"subReqID,omitempty"`
}

func (m *Foo) Reset()                    { *m = Foo{} }
func (m *Foo) String() string            { return proto.CompactTextString(m) }
func (*Foo) ProtoMessage()               {}
func (*Foo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Bar struct {
	SubReqID int32 `protobuf:"varint,1,opt,name=subReqID" json:"subReqID,omitempty"`
}

func (m *Bar) Reset()                    { *m = Bar{} }
func (m *Bar) String() string            { return proto.CompactTextString(m) }
func (*Bar) ProtoMessage()               {}
func (*Bar) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Baz struct {
	SubReqID int32 `protobuf:"varint,1,opt,name=subReqID" json:"subReqID,omitempty"`
}

func (m *Baz) Reset()                    { *m = Baz{} }
func (m *Baz) String() string            { return proto.CompactTextString(m) }
func (*Baz) ProtoMessage()               {}
func (*Baz) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type OneMessage struct {
	// Identifies which field is filled in.
	Type []OneMessage_Type `protobuf:"varint,1,rep,packed,name=type,enum=google.protobuf.OneMessage_Type" json:"type,omitempty"`
	// One of the following will be filled in.
	Foo []*Foo `protobuf:"bytes,2,rep,name=foo" json:"foo,omitempty"`
	Bar []*Bar `protobuf:"bytes,3,rep,name=bar" json:"bar,omitempty"`
	Baz []*Baz `protobuf:"bytes,4,rep,name=baz" json:"baz,omitempty"`
}

func (m *OneMessage) Reset()                    { *m = OneMessage{} }
func (m *OneMessage) String() string            { return proto.CompactTextString(m) }
func (*OneMessage) ProtoMessage()               {}
func (*OneMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *OneMessage) GetFoo() []*Foo {
	if m != nil {
		return m.Foo
	}
	return nil
}

func (m *OneMessage) GetBar() []*Bar {
	if m != nil {
		return m.Bar
	}
	return nil
}

func (m *OneMessage) GetBaz() []*Baz {
	if m != nil {
		return m.Baz
	}
	return nil
}

func init() {
	proto.RegisterType((*Foo)(nil), "google.protobuf.Foo")
	proto.RegisterType((*Bar)(nil), "google.protobuf.Bar")
	proto.RegisterType((*Baz)(nil), "google.protobuf.Baz")
	proto.RegisterType((*OneMessage)(nil), "google.protobuf.OneMessage")
	proto.RegisterEnum("google.protobuf.OneMessage_Type", OneMessage_Type_name, OneMessage_Type_value)
}

func init() { proto.RegisterFile("MyMessage.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xf7, 0xad, 0xf4, 0x4d,
	0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4f, 0xcf, 0xcf,
	0x4f, 0xcf, 0x81, 0xf2, 0x92, 0x4a, 0xd3, 0x94, 0x14, 0xb9, 0x98, 0xdd, 0xf2, 0xf3, 0x85, 0xa4,
	0xb8, 0x38, 0x8a, 0x4b, 0x93, 0x82, 0x52, 0x0b, 0x3d, 0x5d, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58,
	0x83, 0xe0, 0x7c, 0x90, 0x12, 0xa7, 0xc4, 0x22, 0xc2, 0x4a, 0xaa, 0xf0, 0x2a, 0xb9, 0xcb, 0xc8,
	0xc5, 0xe5, 0x9f, 0x97, 0x0a, 0x75, 0x8e, 0x90, 0x09, 0x17, 0x4b, 0x49, 0x65, 0x41, 0xaa, 0x04,
	0xa3, 0x02, 0xb3, 0x06, 0x9f, 0x91, 0x82, 0x1e, 0x9a, 0xbb, 0xf4, 0x10, 0x4a, 0xf5, 0x42, 0x2a,
	0x0b, 0x52, 0x83, 0xc0, 0xaa, 0x85, 0xd4, 0xb8, 0x98, 0xd3, 0xf2, 0xf3, 0x25, 0x98, 0x14, 0x98,
	0x35, 0xb8, 0x8d, 0x44, 0x30, 0x34, 0xb9, 0xe5, 0xe7, 0x07, 0x81, 0x14, 0x80, 0xd4, 0x25, 0x25,
	0x16, 0x49, 0x30, 0xe3, 0x50, 0xe7, 0x94, 0x58, 0x14, 0x04, 0x52, 0x00, 0x51, 0x57, 0x25, 0xc1,
	0x82, 0x53, 0x5d, 0x15, 0x48, 0x5d, 0x95, 0x92, 0x22, 0x17, 0x0b, 0xc8, 0x15, 0x42, 0xec, 0x5c,
	0xcc, 0x6e, 0xfe, 0xfe, 0x02, 0x0c, 0x20, 0x86, 0x93, 0x63, 0x90, 0x00, 0x23, 0x84, 0x11, 0x25,
	0xc0, 0xe4, 0x24, 0xc3, 0x85, 0x1e, 0xb6, 0x4e, 0x9c, 0xf0, 0xd0, 0x4f, 0x62, 0x03, 0x0b, 0x1a,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x24, 0xa6, 0xb4, 0xf8, 0x91, 0x01, 0x00, 0x00,
}
